### ISSUE TITLE
--harmony option prevents startup

### ISSUE THREAD

**Issue by jghaines** [elitechance/api-gateway-sim#2]
Running the follownig test in a node v4.3 environment under docker:

````
$ docker run -it --entrypoint bash node:4.3
# which node
/usr/local/bin/node
# npm install api-gateway-sim --global
...
npm info installOne api-gateway-sim@1.0.10
...
# ags
/usr/bin/env: node --harmony: No such file or directory
````

This looks the same as this [stackoverflow issue](http://stackoverflow.com/questions/24548733/how-to-make-a-nodejs-file-executable-with-harmony-option). Manually implementing the suggested patch solves the issue.

**Comment by elitechance** [comment]
This was also discuss here: https://github.com/nodejs/node-v0.x-archive/issues/3911
So others tried to make node visible in common paths like /usr/bin/ or /usr/local/bin.  And in debian or other linux variants, node is actually nodejs.  What they normally do is to add sym link as node.

**Comment by jghaines** [comment]
node is in the path. The error is not:

"*node*" : No such file or directory

The error is 

"*node --harmony*" : No such file or directory

I've updated the original issue to show that node is in the path.

**Comment by elitechance** [comment]
I get it now.  I'll be removing --harmony to solve this issue.
